# Settings for a local WiFi network for the toy to connect to. This allows you
# to access the toy without having to switch to its own WiFi network. You can
# configure the SSID and password in the UI without needing to reflash the
# firmware; these settings are just the defaults, which gives you the option to
# have WiFi configured out of the box.
[wifi]
# The hostname of the toy on the local network. If the hostname is `foo`, you
# can access the toy at `http://foo.local` (with clients that support mDNS).
hostname = "squirtinator"
# Configuring an SSID will prompt the toy to try and connect to the local
# network.
#ssid = "MyNetwork"
#password = "12345"

  # You can optionally assign the toy a static IP address on the local network.
  #[wifi.static]
  #addr = "192.168.0.69"
  #gateway = "192.168.0.1"
  #mask = 24

# Settings for the toy's own WiFi network. This allows you to connect to the
# toy when there's not a local WiFi network available, or to change the WiFi
# SSID/password without already being connected (to avoid a chicken-and-egg
# problem).
[access_point]
ssid = "Squirtinator"
hidden = false
gateway = "192.168.0.1"
#channel = 1
#password = "correct horse battery staple"

[http]
port = 80

[io]
# The GPIO pin to send a pulse to when the toy is activated.
pin = 0
# The duration of the pulse, in milliseconds.
duration = 500
