[wifi]
ssid = "Squirtinator"
hidden = false
#channel = 1
#password = "correct horse battery staple"

[http]
port = 80

[io]
# The GPIO pin to send a pulse to when the toy is activated.
pin = 0
# The duration of the pulse, in milliseconds.
duration = 500
