# Settings for a local WiFi network for the toy to connect to. This allows you
# to access the toy without having to switch to its own WiFi network. You can
# always configure the SSID and password in the UI without needing to reflash
# the firmware; these settings are just the defaults, which gives you the
# option to have WiFi configured out of the box.
[wifi]
# Configuring an SSID will prompt the toy to try and connect to the local
# network.
#ssid = "MyNetwork"
#password = "12345"

# The hostname of the toy on the local network. If the hostname is `foo`, you
# can access the toy at `http://foo.local` (with clients that support mDNS).
# Change this if you plan to have multiple Squirtinators on the same network.
hostname = "squirtinator"

  # You can optionally assign the toy a static IP address on the local network.
  #[wifi.static]
  #addr = "192.168.0.69"
  #gateway = "192.168.0.1"
  #mask = 24

# Settings for the toy's own WiFi hotspot. This allows you to connect to the
# toy when there's not a local WiFi network available, or to configure the
# SSID/password of the local WiFi network without already being connected (to
# avoid a chicken-and-egg problem).
[access_point]
ssid = "Squirtinator"
#password = "correct horse battery staple"
hidden = false
gateway = "192.168.0.1"
#channel = 1

[http]
port = 80

[io]
# The GPIO pins to use for communicating with the pump controller over I2C.
sda_pin = 0
scl_pin = 1
# The I2C address of the pump controller.
address = 0x01
# The message to send to the pump controller to trigger a squirt.
message = []
# The baud rate.
baudrate = 1_000_000
# The timeout for I2C writes, in milliseconds.
timeout = 100
# The minimum amount of time allowed between I2C writes, in milliseconds.
# Attempts to activate the pump more frequently than this are ignored.
block_time = 500
# When in test mode, the actual I2C call is skipped. Useful for testing when
# there's no target device connected.
test_mode = true

# These settings control how frequently the toy will squirt. The user selects a
# minimum and maximum duration, and the toy will randomly select a duration
# within that range to wait before squirting again.
[frequency]
# These control the lower and upper bounds of the range sliders in the settings
# menu.
lower_bound = 0
upper_bound = 300

# These control the default minimum and maximum values, which the user can
# adjust in the settings menu.
default_min = 30
default_max = 120
