# Settings for a local WiFi network for the toy to connect to. This allows you
# to access the toy without having to switch to its own WiFi network. You can
# always configure the SSID and password in the UI without needing to reflash
# the firmware; these settings are just the defaults, which gives you the
# option to have WiFi configured out of the box.
[wifi]
# Configuring an SSID will prompt the toy to try and connect to the local
# network.
#ssid = "MyNetwork"
#password = "12345"

# The hostname of the toy on the local network. If the hostname is `foo`, you
# can access the toy at `http://foo.local` (with clients that support mDNS).
# Change this if you plan to have multiple Squirtinators on the same network.
hostname = "squirtinator"

# The timeout between connection attempts, in seconds.
timeout = 15

# The number of attempts the toy will make to connect to the local network
# before falling back to only running in access point mode.
max_attempts = 4

  # You can optionally assign the toy a static IP address on the local network.
  #[wifi.static]
  #addr = "192.168.0.69"
  #gateway = "192.168.0.1"
  #mask = 24

# Settings for the toy's own WiFi hotspot. This allows you to connect to the
# toy when there's not a local WiFi network available, or to configure the
# SSID/password of the local WiFi network without already being connected (to
# avoid a chicken-and-egg problem).
[access_point]
ssid = "Squirtinator"
#password = "correct horse battery staple"
hidden = false
gateway = "192.168.0.1"
#channel = 1

[http]
port = 80

[io]
# The GPIO pin to send a pulse to when the toy is activated.
pin = 0
# The duration of the pulse, in milliseconds.
duration = 500
